version: '3'

tasks:
  default:
    - task: run

  run:
    cmds:
      - task build-debug
      - ./build/debug/main.exe

  run-release:
    cmds:
      - task build-release
      - ./build/release/main.exe

  run-meta:
    cmds:
      - odin run meta -out:build/meta.exe -debug

  debug:
    cmds:
      - task build-debug
      - powershell ./debug-rad.ps1

  build-shaders:
    sources:
      - shaders/**/*.slang
    cmds:
      - pwsh ./build-shaders.ps1

  build-debug:
    deps: [build-shaders]
    cmds:
      - pwsh ./build-debug.ps1

  build-release:
    deps: [build-shaders]
    cmds:
      - pwsh ./build-release.ps1

  check:
    cmds:
      - odin check . -strict-style -warnings-as-errors -vet

  test:
    cmds:
      - odin test src -collection:deps=deps -debug -ignore-unknown-attributes

